steps:
  - name: gcr.io/cloud-builders/docker
    id: Pull cache
    entrypoint: bash
    args:
      - -lc
      - docker pull ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:buildcache || true

  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --cache-from
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:buildcache
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:buildcache
      - -f
      - ${_DOCKER_CONTEXT}/${_DOCKERFILE}
      - ${_DOCKER_CONTEXT}

  - name: gcr.io/cloud-builders/docker
    id: Push commit
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}

  - name: gcr.io/cloud-builders/docker
    id: Push cache
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:buildcache

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --platform=managed
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-id=${_TRIGGER_ID}
      - --region=${_DEPLOY_REGION}
      - --quiet

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy worker
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_WORKER_SERVICE_NAME}
      - --platform=managed
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-id=${_TRIGGER_ID}
      - --region=${_DEPLOY_REGION}
      - --quiet

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: Deploy beat
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_BEAT_SERVICE_NAME}
      - --platform=managed
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-id=${_TRIGGER_ID}
      - --region=${_DEPLOY_REGION}
      - --quiet

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:buildcache

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TRIGGER_ID: 6582dceb-3e12-41be-a116-7f13cb4bb9c8
  _AR_HOSTNAME: australia-southeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: balmy-atom-484923-m2
  _PLATFORM: managed
  _SERVICE_NAME: centracortex
  _WORKER_SERVICE_NAME: centracortex-worker
  _BEAT_SERVICE_NAME: centracortex-beat
  _DOCKER_CONTEXT: backend
  _DOCKERFILE: Dockerfile
  _DEPLOY_REGION: australia-southeast1
  REPO_NAME: centracortex

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - centracortex
